import { GeniusConfigurationType } from '../types/config/GeniusConfiguration'

const GeniusConfiguration: GeniusConfigurationType = {
  navigation: {
    isToolsPageDisplayed: false,
    isServicesPageDisplayed: true,
    isProductsPageDisplayed: true,
    isPricingPageDisplayed: true,
    isMoreSubNavDisplayed: true,
    isBlogPageDisplayed: true,
    isCartIconEnabled: true,
    isAccountIconEnabled: true,
    isSearchIconEnabled: true,
  },
  routes: {
    isHomePageEnabled: true,
    isFeaturesPageEnabled: true,
    isPricingPageEnabled: true,
    isContactPageEnabled: true,
    isAboutUsPageEnabled: true,
    isPressPageEnabled: false,
    isPrivacyPolicyPageEnabled: true,
    isTermsOfServicePageEnabled: true,
    isBlogPageEnabled: true,
    isBlogPostPageEnabled: true,
    isDevelopersPageEnabled: false,
    isForumsPageEnabled: false,
    isForumTopicPageEnabled: false,
    isLoginPageEnabled: true,
    isHelpPageEnabled: true,
    isSignUpPageEnabled: true,
    isAccountPageEnabled: true,
    isAccountSettingsPageEnabled: true,
    isSearchPageEnabled: true,
    isNewsletterSignUpPageEnabled: true,
    isComingSoonPageEnabled: false,
    isMaintenancePageEnabled: false,
    isPasswordResetPageEnabled: true,
    isDashboardPageEnabled: true,
    isNotFoundPageEnabled: true,
  },
  seo: {
    metaData: {
      robots: { name: 'robots', content: 'index, follow' },
      viewport: {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1',
      },
      contentType: {
        'http-equiv': 'Content-Type',
        content: 'text/html; charset=UTF-8',
      },
      xUACompatible: { 'http-equiv': 'X-UA-Compatible', content: 'IE=edge' },
      ogType: { property: 'og:type', content: 'website' },
      ogLocale: { property: 'og:locale', content: 'en_US' },
      twitterCard: { name: 'twitter:card', content: 'summary_large_image' },
      twitterSite: { name: 'twitter:site', content: '@example' },
      twitterCreator: { name: 'twitter:creator', content: '@example_creator' },
      themeColor: { name: 'theme-color', content: '#ffffff' },
      msTileColor: { name: 'msapplication-TileColor', content: '#da532c' },
      msConfig: { name: 'msapplication-config', content: '/browserconfig.xml' },
    },
    linkTags: {
      manifest: { rel: 'manifest', href: '/manifest.json' },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: 'Example Inc.',
      url: 'https://www.example.com',
      logo: 'https://www.example.com/logo.png',
      sameAs: [
        'https://www.facebook.com/example',
        'https://twitter.com/example',
      ],
      contactPoint: {
        '@type': 'ContactPoint',
        email: 'info@example.com',
        contactType: 'customer service',
        areaServed: 'US',
        availableLanguage: ['English', 'Spanish'],
      },
      hasPart: {
        '@type': 'LocalBusiness',
        name: 'Example Store',
        url: 'https://store.example.com',
        address: {
          '@type': 'PostalAddress',
          streetAddress: '123 Example Street',
          addressLocality: 'Example City',
          addressRegion: 'CA',
          postalCode: '90001',
          addressCountry: 'USA',
        },
        telephone: '+1-123-456-7890',
        openingHours: 'Mo-Fr 09:00-18:00',
        geo: {
          '@type': 'GeoCoordinates',
          latitude: '34.0522',
          longitude: '-118.2437',
        },
      },
    },
  },
}

export default GeniusConfiguration
